[build]
  publish = "dist"
  command = "yarn build && yarn generate"

[build.environment]
  NODE_VERSION = "16.14.0"  # Updated to a specific, available Node.js version
  NODE_OPTIONS = "--openssl-legacy-provider"

[context.production]
  command = "yarn build && yarn generate"

[context.branch-deploy]
  command = "yarn build && yarn generate"

[context.deploy-preview]
  command = "yarn build && yarn generate"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

  [plugins.inputs]
    debug = true
