name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn install

      - name: Build and Generate static files
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          yarn build
          yarn generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'nuxt-static'
          path: dist  # Assuming the generated static files are in the 'dist' directory



  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: 'nuxt-static'  # This should match the name used in the upload step

