
name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn install

      - name: Build with Nuxt
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn build

      - name: Generate static files
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: yarn generate

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'nuxt-static'  # Use 'name' instead of 'artifact_name'
          path: .nuxt/dist  # Ensure this is the correct path to your build output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: main # Ensure this is the correct branch for GitHub Pages deployment
          folder: nuxt-static # This should match the artifact_name used in the upload step
